In [14]:
import pandas as pd
df = pd.read_csv('學生成績.csv')

def less60(v,prop=''):
    return prop if v<60 else None

df.style\
.map(less60,prop='color:red',subset=["國文","英文","數學","生物","歷史"])\
.format(precision=2,subset=["平均"])

In [15]:
df.iloc[2]

學號       3
姓名     李政白
國文      70
英文      78
數學      59
歷史      60
生物      50
總分     317
平均    63.4
Name: 2, dtype: object

In [27]:
name_s=df['姓名']
print(name_s[4])
print("=========")
display(pd.DataFrame(name_s[:5]))
print("=========")
print(name_s[-3:])
print("=========")
print(name_s[5:13])

戚亨
=========

    姓名
0  龐皓芳
1  蔡欣汝
2  李政白
3  錢欣潔
4   戚亨

=========
27    楊易政
28    林康亮
29    陳得映
Name: 姓名, dtype: object
=========
5     林希啟
6     盧冠發
7     許淑婷
8     張慧君
9     游倫城
10    李慈啟
11    王怡君
12    黃婷婷
Name: 姓名, dtype: object

In [29]:
df[["姓名","國文","英文","數學"]]

     姓名  國文   英文   數學
0   龐皓芳  55   80   81
1   蔡欣汝  76   57   91
2   李政白  70   78   59
3   錢欣潔  67   72   95
4    戚亨  69   88   89
5   林希啟  67   54   60
6   盧冠發  59   62   51
7   許淑婷  68   84   99
8   張慧君  73   97  100
9   游倫城  72   70   57
10  李慈啟  70   55   78
11  王怡君  82   94   56
12  黃婷婷  71   51   88
13  杜明延  70   80   63
14  唐雪豪  68   95   59
15  孫火清  66   77   68
16  陳逸凡  99   81   65
17  張雅芬  74   52   87
18  張伊映  83   95   96
19  陳倩潔  91  100   84
20  黃佩芬  78   74   50
21  林志成  86   62   77
22  簡美君  51   85   52
23  陳嘉淑  67   59   63
24  王士銘  60   80   70
25  吳柏誠  65   64   60
26  黃必琪  71   90   63
27  楊易政  63   57   56
28  林康亮  96   65   84
29  陳得映  84   62   72