In [7]:
import pandas as pd
df=pd.read_csv('學生成績.csv')
df.index=df['學號']
df1=df.drop(columns='學號')

In [15]:
df1['排名']=df1['平均'].rank(method='min',ascending=False)
df2=df1.sort_values(by='平均',ascending=False)
df2

     姓名  國文   英文   數學   歷史   生物   總分    平均    排名
學號
19  張伊映  83   95   96   87   80  441  88.2   1.0
9   張慧君  73   97  100   74   85  429  85.8   2.0
29  林康亮  96   65   84  100   84  429  85.8   2.0
17  陳逸凡  99   81   65   72   98  415  83.0   4.0
4   錢欣潔  67   72   95   98   80  412  82.4   5.0
12  王怡君  82   94   56   83   96  411  82.2   6.0
20  陳倩潔  91  100   84   65   62  402  80.4   7.0
25  王士銘  60   80   70   81  100  391  78.2   8.0
1   龐皓芳  55   80   81   84   84  384  76.8   9.0
21  黃佩芬  78   74   50   90   92  384  76.8   9.0
5    戚亨  69   88   89   85   51  382  76.4  11.0
15  唐雪豪  68   95   59   88   70  380  76.0  12.0
18  張雅芬  74   52   87   72   92  377  75.4  13.0
13  黃婷婷  71   51   88   76   89  375  75.0  14.0
2   蔡欣汝  76   57   91   74   73  371  74.2  15.0
8   許淑婷  68   84   99   52   61  364  72.8  16.0
22  林志成  86   62   77   69   65  359  71.8  17.0
14  杜明延  70   80   63   53   89  355  71.0  18.0
11  李慈啟  70   55   78   57   91  351  70.2  19.0
30  陳得映  84   62   72   68   63  349  69.8  20.0
6   林希啟  67   54   60   67  100  348  69.6  21.0
16  孫火清  66   77   68   74   62  347  69.4  22.0
27  黃必琪  71   90   63   67   54  345  69.0  23.0
28  楊易政  63   57   56   76   88  340  68.0  24.0
7   盧冠發  59   62   51   85   74  331  66.2  25.0
10  游倫城  72   70   57   56   68  323  64.6  26.0
3   李政白  70   78   59   60   50  317  63.4  27.0
23  簡美君  51   85   52   71   56  315  63.0  28.0
24  陳嘉淑  67   59   63   50   62  301  60.2  29.0
26  吳柏誠  65   64   60   51   61  301  60.2  29.0

In [19]:
df2.head(n=10)

     姓名  國文   英文   數學   歷史   生物   總分    平均   排名
學號
19  張伊映  83   95   96   87   80  441  88.2  1.0
9   張慧君  73   97  100   74   85  429  85.8  2.0
29  林康亮  96   65   84  100   84  429  85.8  2.0
17  陳逸凡  99   81   65   72   98  415  83.0  4.0
4   錢欣潔  67   72   95   98   80  412  82.4  5.0
12  王怡君  82   94   56   83   96  411  82.2  6.0
20  陳倩潔  91  100   84   65   62  402  80.4  7.0
25  王士銘  60   80   70   81  100  391  78.2  8.0
1   龐皓芳  55   80   81   84   84  384  76.8  9.0
21  黃佩芬  78   74   50   90   92  384  76.8  9.0

In [20]:
df2.tail(n=10)

     姓名  國文  英文  數學  歷史   生物   總分    平均    排名
學號
6   林希啟  67  54  60  67  100  348  69.6  21.0
16  孫火清  66  77  68  74   62  347  69.4  22.0
27  黃必琪  71  90  63  67   54  345  69.0  23.0
28  楊易政  63  57  56  76   88  340  68.0  24.0
7   盧冠發  59  62  51  85   74  331  66.2  25.0
10  游倫城  72  70  57  56   68  323  64.6  26.0
3   李政白  70  78  59  60   50  317  63.4  27.0
23  簡美君  51  85  52  71   56  315  63.0  28.0
24  陳嘉淑  67  59  63  50   62  301  60.2  29.0
26  吳柏誠  65  64  60  51   61  301  60.2  29.0

In [21]:
df2.query('排名<=10')

     姓名  國文   英文   數學   歷史   生物   總分    平均   排名
學號
19  張伊映  83   95   96   87   80  441  88.2  1.0
9   張慧君  73   97  100   74   85  429  85.8  2.0
29  林康亮  96   65   84  100   84  429  85.8  2.0
17  陳逸凡  99   81   65   72   98  415  83.0  4.0
4   錢欣潔  67   72   95   98   80  412  82.4  5.0
12  王怡君  82   94   56   83   96  411  82.2  6.0
20  陳倩潔  91  100   84   65   62  402  80.4  7.0
25  王士銘  60   80   70   81  100  391  78.2  8.0
1   龐皓芳  55   80   81   84   84  384  76.8  9.0
21  黃佩芬  78   74   50   90   92  384  76.8  9.0

In [28]:
df2.to_excel('學生成績單.xlsx',sheet_name='2年13班成績單')